name: Run Monthly Forecast Script

on:
  schedule:
    - cron: '0 2 1 * *'  # ทุกวันที่ 1 ของเดือน เวลา 09:00 (ไทย)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run forecast script
        run: |
          python forecast.py
